# Generated by Django 4.2.1 on 2023-05-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memo", "0002_alter_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
