# Generated by Django 4.2.1 on 2023-05-22 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("memo", "0003_alter_post_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="id",
            new_name="memo_id",
        ),
    ]
