# Generated by Django 4.2.1 on 2023-05-24 15:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("memo", "0005_alter_post_memo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="memo_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
