# Generated by Django 4.2.2 on 2023-07-17 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Passwordは大文字・小文字・数字・記号のうち少なくとも2種類を含める必要があります。', regex='^(?=.*?[a-z])(?=.*?[0-9]).*$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
